cicd updated

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -58,20 +58,22 @@ jobs:
           # Add EC2 public IP to known_hosts
           ssh-keyscan -H $AWS_EC2_PUBLIC_IP >> ~/.ssh/known_hosts
 
-          # Debugging steps
-          echo "Current Directory:"
-          pwd
-          echo "Files:"
-          ls -la
-          echo "Known Hosts:"
-          cat ~/.ssh/known_hosts
-          echo "EC2 Key Permissions:"
-          ls -l ec2-key.pem
-
           ssh -i ec2-key.pem ubuntu@$AWS_EC2_PUBLIC_IP << 'EOF'
+            # Install Docker if not present
+            if ! command -v docker &> /dev/null; then
+              echo "Docker not found, installing..."
+              sudo apt update
+              sudo apt install -y docker.io
+              sudo systemctl start docker
+              sudo systemctl enable docker
+            else
+              echo "Docker is already installed."
+            fi
+
             docker stop oj-server || true
             docker rm oj-server || true
             docker image prune -af
+
             docker pull $REPO_URI/oj-server:${{ github.sha }}
             docker run -d --name oj-server -p 5000:5000 $REPO_URI/oj-server:${{ github.sha }}
           EOF
