pipeline changed

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -69,6 +69,17 @@ jobs:
             else
               echo "Docker is already installed."
             fi
+            
+            # Install AWS CLI if not present
+            if ! command -v aws &> /dev/null; then
+              echo "AWS CLI not found, installing..."
+              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+              unzip awscliv2.zip
+              sudo ./aws/install
+              rm -rf awscliv2.zip aws
+            else
+              echo "AWS CLI is already installed."
+            fi
 
             # Log in to ECR on EC2
             aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin ${{ env.REPO_URI }}
